Repository nextcloud/hmr_enabler, pull requests merged in 2023-05, with the labels that each got.

#35 docs: Add information what's needed on app side
  README.md
Labels: 3. to review

#28 Updating phpunit-pgsql.yml workflow from template
  .github/workflows/phpunit-pgsql.yml
Labels: dependencies

#39 chore: update workflows from templates
  .github/workflows/command-rebase.yml
  .github/workflows/lint-info-xml.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/psalm.yml
Labels: 3. to review, dependencies, automated
